version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: skydash-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_super_secret
      MYSQL_DATABASE: skydash_db
      MYSQL_USER: skydash_user
      MYSQL_PASSWORD: user_password_secret
    ports:
      - "3307:3306"
    volumes:
      - skydash-db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: skydash-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=skydash_user
      - DB_PASSWORD=user_password_secret
      - DB_NAME=skydash_db
      - JWT_SECRET=INI_RAHASIA_BANGET_JANGAN_SAMPE_BOCOR_GANTI_INI
    volumes:
      - ./backend/whatsapp_auth_info:/usr/src/app/whatsapp_auth_info
      - ./backend/public/uploads/avatars:/usr/src/app/public/uploads/avatars
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skydash-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  skydash-db-data: